name: Run Plugin Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'version.py'
      - 'test/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  plugin_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: |
          pip install pytest pytest-timeout pytest-cov
      - name: Install ovos dependencies
        run: |
          pip install ovos-plugin-manager ovos-core~=0.0.2a12[skills]
      - name: Install package
        run: |
          pip install .
      - name: Run Plugin tests
        run: |
          pytest test/plugin_tests.py
